### ISSUE TITLE
Splice inside nested parens

### ISSUE THREAD

**Issue by bfabry** [parinfer/parinfer.js#107]
I don't know if this is really a bug, maybe a bug in the documentation? But the documentation says you can get the behaviour of Splice by deleting an opening paren, however with nested functions you don't really get that.

https://shaunlebron.github.io/parinfer/#deleting-parens

```
(foo (bar 1 2 3 4 5 6) bash baz)
delete the paren opening before bar =>
(foo bar 1 2 3 4 5 6) bash baz
```

Obviously consistent with the rules, but not the behaviour of splice.

**Comment by shaunlebron** [comment]
Sorry about this.  Thanks for reporting.  This fits into a class of errors that was recently discovered.  Tracking in #108
