### ISSUE TITLE
Parinfer does not correctly handle square brace characters

### ISSUE THREAD

**Issue by cursive-ghost** [parinfer/parinfer.js#109]
It is impossible to enter the following code:

```
{:tag-open \[ :tag-close \]}
{:tag-open \[ :tag-close \]}
```

See cursive-ide/cursive#1342.

**Comment by shaunlebron** [comment]
Should be fixed in 1.7.1.  Thanks for relaying the issue!

**Comment by sveri** [comment]
Thanks for the fix :-)
