### ISSUE TITLE
Incorrect Parinfer for def with ^doc note

### ISSUE THREAD

**Issue by dimitertodorov** [parinfer/parinfer.js#113]
Not sure why this does not work.

Valid code is:

``` clojure
(def ^{:doc "websocket channel"}
ws-ch
  (chan))
```

Parinfer incorrectly formats it to:

``` clojure
(def ^{:doc "websocket channel"})
ws-ch
  (chan)
```

The following works fine.

``` clojure
(def ^{:doc "websocket channel"} ws-ch
  (chan))
```

**Comment by shaunlebron** [comment]
Hi @dimitertodorov, a child line must always be indented at least one space to the right of the parent open-paren.  This will work fine:

``` clj
(def ^{:doc "websocket channel"}
 ws-ch
  (chan))
```

**Comment by shaunlebron** [comment]
If you are ever uncertain about things like this, it is safe to just try different indentation lengths.  Indentation is the only thing really happening here.  I'll close this, but let me know if you have other questions.
