### ISSUE TITLE
Lisp variant-specific indent

### ISSUE THREAD

**Issue by bpstahlman** [parinfer/parinfer.js#116]
Given that Parinfer knows nothing about the lisp variant-specific indentation conventions... Is the "parinfer way" to ignore such conventions, contenting oneself with a shiftwidth-based indentation, which satisfies parinfer's invariant without conforming to any particular lisp style guide? Or is the idea that you should always use parinfer in conjunction with a variant-specific plugin that understands the lisp variant's indentation preferences? And if it's the latter, how would it work? Intuitively, I would think that the variant-specific plugin would handle indents/dedents and then pass the resulting text to indentParinfer() to adjust the parens. But while reading the section "Adding Parinfer to an Editor" on the npmjs site, I saw this:
- Use Tab Stops to allow the user to quickly indent/dedent lines to important points in Indent Mode. When the user presses Tab or Shift+Tab, do the following:
  - _Prevent Tab from doing its normal space insertion, or just remove them prior to the next step._
  - Run Indent Mode on the text, passing the cursor in as normal. BUT, if you have multiple lines selected, you must instead pass in the starting position of the selection as the cursor.

**Question:** If we don't add any tabs/spaces prior to the call to indentMode, how will the correct parens be calculated? Or am I misunderstanding what is meant by "Prevent Tab from doing its normal space insertion"? E.g., perhaps it simply means don't allow tab to be converted to spaces?

Is this project meant to be used in conjunction with lisp variant-specific indent plugins, or standalone?

**Comment by shaunlebron** [comment]
I have a longer answer to this which I will have to write later if needed.  But quickly:
- the hope is that variant-specific indent plugins will work with parinfer, as long as they don't go against its invariant
- I tried clarifying the Use Tab Stops section here: https://github.com/shaunlebron/parinfer/commit/648b21e0e487f3ace369d4e9a1a3b54a35e6653a.  The idea is that I can't predict the variant-specific indents, so I don't do anything but _give_ you the information about critical tab-stops according to the invariant.  You have to **re-run** indent mode after inserting the correct number of spaces.

**Comment by bpstahlman** [comment]
Thanks. The clarification regarding the need to _re-run_ indent mode was the missing piece. Do I assume correctly that the term "same delta" refers to "virtual spaces" (i.e., horizontal screen distance) rather than literal tabs/spaces? I.e., the plugin would decide (possibly as a function of editor's 'expandtab', 'tabstop', etc...) whether to achieve the "delta" using tabs, spaces, or a mixture thereof?

**Comment by shaunlebron** [comment]
I actually do away with "virtual spaces" by adopting Clojure's no-tab convention.  I will put this in the readme somewhere, but i wrote a little about it here: https://github.com/shaunlebron/parinfer/blob/master/lib/parinfer.js.md#tab-characters).

I suppose it's possible to work with tabs by adding an extra `tabWidth` config.  It just seems simpler to not consider tabs.

**Comment by bpstahlman** [comment]
I suppose disallowing tabs makes sense. I used to be a big proponent of using tabs for leading indent, and I still think it makes sense in many contexts, but for languages that require things to be aligned at x positions that don't always correspond with a multiple of the shiftwidth, tabs can really complicate matters, and may not be worth it...

**Comment by shaunlebron** [comment]
I'll reopen if there are more questions

**Comment by bpstahlman** [comment]
Thanks!
