### ISSUE TITLE
Document that tab characters are converted to two spaces

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#117]
In reference to https://github.com/shaunlebron/parinfer/issues/116#issuecomment-239623133, I need to clarify why tab characters are transformed to two spaces (i.e. to prevent ambiguity of indentation lengths)

**Comment by shaunlebron** [comment]
I suppose I already documented it here https://github.com/shaunlebron/parinfer/blob/master/lib/parinfer.js.md#tab-characters, but it should be mentioned in the readme

**Comment by Kurvivor19** [comment]
Probably amount of spaces should be customizeable
I have seen cases (for example, when opening emacs sources with parinfer  active) where that assumption wrecked files.
On the other hand, i was probably using parinfer in the wrong mode

**Comment by shaunlebron** [comment]
i think this is a common enough convention and I can't find a place in the readme for it really.

@Kurvivor19 yeah, I think it's related to note running paren mode first
