### ISSUE TITLE
missing semicolon breaks `:simple` and `:whitespace` compiler modes

### ISSUE THREAD

**Issue by darwin** [parinfer/parinfer.js#120]
https://github.com/shaunlebron/parinfer/blob/648b21e0e487f3ace369d4e9a1a3b54a35e6653a/lib/parinfer.js#L55

proof:
https://dl.dropboxusercontent.com/u/559047/missing-semicolons-might-kill-people-one-day-when-javascript-is-used-in-self-driving-cars.png

**Comment by shaunlebron** [comment]
thanks for reporting, i'm surprised closure minifies by joining lines like that.  I added a lint rule to see if semicolons were missing elsewhere and they were.  fixed.

published 1.8.2 with the fixes
