### ISSUE TITLE
A new parinfer-mode for Emacs.

### ISSUE THREAD

**Issue by DogLooksGood** [parinfer/parinfer.js#122]
Recently I'm working on a new parinfer-mode for emacs, and here's the project: https://github.com/DogLooksGood/parinfer-mode

I start this for some reasons:
- My friends are complaining that when using Parinfer on an old file, the modification is uncontrolled. So I want to provide a way to see how Parinfer changes code.
- Currently there are a lot of parinfer-mode in Emacs, but none of them can satisfy me. Maybe some bugs or the slow performance.
- Emacs usually provide a good indentation spec for languages (specially Clojure), and I hope Parinfer can use these indent rules.

I hope this plugin can be listed in the plugin list.
Thanks very much.

**Comment by shaunlebron** [comment]
Thanks, published changes to the site 👍
