### ISSUE TITLE
Parinfer with Geany ?

### ISSUE THREAD

**Issue by Adrien79** [parinfer/parinfer.js#128]
This project looks good. Would it be easy to make it work with the Geany IDE?

Context: Geany is lightweight and a plugin already exists to integrate a REPL, but it is lacking a proper auto-indentation and parens management tool to make a decent Lisp environment.

**Comment by shaunlebron** [comment]
what language can the plugins be written in?

**Comment by Adrien79** [comment]
In C or C++ as far as I know, here are the docs I could find:
https://www.geany.org/manual/reference/howto.html
https://www.geany.org/manual/reference/guidelines.html

**Comment by shaunlebron** [comment]
@Adrien79 thanks for the info!  we currently don't have a C port.  I started one here some time ago: https://github.com/shaunlebron/parinfer.cpp

I currently don't have bandwidth for this right now, but I'll leave open for others.

**Comment by shaunlebron** [comment]
There are talks of porting to parinfer-rust to c, but currently the vim plugin shells out to a parinfer-rust executable, which is also used by parinfer-rust-mode.  It seems fast enough that you won’t have to wait for a language port.
