### ISSUE TITLE
Incorrect treatment of `"` inside `;` comments

### ISSUE THREAD

**Issue by fhur** [parinfer/parinfer.js#129]
The following is marked by parinfer as unformatted. Its because of the `"` inside the comments.

```clojure
{:key 1 ;; hello"
 :bar 2}
```

I'm using atom-parinfer 1.17.0. I'm not sure if I should be opening this issue here or there. By the way: parinfer is amazing.

**Comment by shaunlebron** [comment]
we have to heed the warning that comments must have balanced quotes to prevent possible corruption.  an example is shown here: http://shaunlebron.github.io/parinfer/#inserting-quotes

**Comment by fhur** [comment]
Gotcha. I completely missed that one. I'm gonna close this then.

**Comment by shaunlebron** [comment]
np, thanks!
