### ISSUE TITLE
Publish a formatter to allow using Parinfer on teams

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#132]
Using Parinfer on a team is difficult because it can result in large formatting diffs.

We can solve this for teams by creating a formatting tool to standardize 1) close-paren positions and 2) indentation thresholds before each commit.  This is what Paren Mode does, which I think is an easier sell rather than running a full formatter like [cljfmt](https://github.com/weavejester/cljfmt) or [zprint](https://github.com/kkinnear/zprint).

The tool could be integrated into CI like a linter, to ensure the formatting rules are followed on the project, allowing Parinfer-crafted commits to not result in large formatting diffs.

original discussion: https://github.com/oakmac/atom-parinfer/issues/77

**Comment by oakmac** [comment]
This does not need to be a large project IMO. Could just be a small node.js script that uses [glob](https://github.com/isaacs/node-glob) with some smart command-line option flags.

**Comment by shaunlebron** [comment]
Yeah, I'll by copying the cli options from [prettier](https://github.com/prettier/prettier)

**Comment by shaunlebron** [comment]
going to put it in the `lib/bin` folder, with a README that describes its usage.

**Comment by oakmac** [comment]
This should be it's own project.

**Comment by shaunlebron** [comment]
published: https://github.com/shaunlebron/parlinter
