### ISSUE TITLE
Port test environment to other implementations?

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#139]
I changed the test environment to be more visual, but this has some implications on how we can test ports.  We can get away with just generating JSON data with text/options as we did before.  We can also go further and have something print out the result using test annotations to make it easier to read them.

**Comment by oakmac** [comment]
Yes - this is essential for the ports to maintain the same test coverage. The test cases should be in a portable format like JSON.

The custom markdown + test annotations is a neat system that is ultimately a distinct problem from Parinfer core logic. `parinfer.js` should not contain any "testing logic".

**Comment by shaunlebron** [comment]
I'll move the test stuff out of `parinfer.js` into a published `test.js`, so it can be used with:

```js
require('parinfer/test');
```

I'll then have our test process generate the JSON data so the ports won't have to use it.

**Comment by shaunlebron** [comment]
published and documented here: https://github.com/shaunlebron/parinfer/tree/master/lib#test-api

I still need to:

- add `parseOutput`
- dump input options and result output data in JSON test case files for ports

**Comment by shaunlebron** [comment]
dumped all parsed test case data into the json files again.  last thing I'll do is to run the tests using this data with the public API to verify.

**Comment by shaunlebron** [comment]
@oakmac all done here I think:

- test parser/printer code moved to [test.js](https://github.com/shaunlebron/parinfer/blob/master/lib/test.js)
- JSON files have a new [format](https://github.com/shaunlebron/parinfer/tree/master/lib/test/cases#parinfer-test-cases) with all the data needed by ports
- added "structure" tests alongside "string" tests in [cases.js](https://github.com/shaunlebron/parinfer/blob/master/lib/test/cases.js) so core API is tested directly
