### ISSUE TITLE
parenTrails empty after clamp

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#166]
the paren trail clamped by the cursor is not remembered below, (i.e. `parenTrails` is empty).

I think it has something to do with `onIndent` not being called at the end since parenStack is empty at `a`.

```js
const code = `
(foo)|
a
`;

const {text, options} = parinferTest.parseInput(code);
options.returnParens = true;

const result = parinfer.smartMode(text, options);

console.log(JSON.stringify(result, null, 2));
```

**Comment by oakmac** [comment]
Where is the test case for this?
