### ISSUE TITLE
multiple indents from wrap

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#173]
Parinfer does not handle the list of changes in the following example.  (operation wraps and formats an expression)

Sandbox code:

```js
const code = `
((reduce-kv (fn [m k v]
            {}
            {})))
`;

console.log(parinfer.smartMode(code, {
  changes: [
    {lineNo:1, x:0, oldText: '', newText: '('},
    {lineNo:2, x:11, oldText: '', newText: ' '},
    {lineNo:3, x:11, oldText: '', newText: ' '},
    {lineNo:3, x:16, oldText: '', newText: ')'},
  ],
}).text);
```

produces:

```clj
((reduce-kv (fn [m k v]
            {
            {}})))
```

**Comment by cursive-ghost** [comment]
Minor nitpick - the last `newText` should be `)` (closing paren), not `(`. It doesn't seem to affect the bug though.

**Comment by shaunlebron** [comment]
ah yes, thanks.  it doesn't affect the bug because parinfer currently only uses the length of `newText`.
