### ISSUE TITLE
Incorrect result when wrapping forms

### ISSUE THREAD

**Issue by cursive-ghost** [parinfer/parinfer.js#176]
When wrapping an existing form, parinfer currently produces a broken result. I start with:

```clojure
(let [a 1]
  (foo))
```

I want to wrap `(foo)` in another form, perhaps an `if`. So I create a new line:

```clojure
(let [a 1]
  |
  (foo))
```

And then wrap the following form. This will cause an open paren to be inserted at the caret, and a close paren to be inserted after the `(foo)`. Cursive will also indent the `(foo)`.

Sandbox code to reproduce:

```javascript
const code = `
(let [a 1]
  (
    (foo)))
`;

console.log(parinfer.smartMode(code, {
  changes: [
    {lineNo:2, x:2, oldText: '', newText: '('},
    {lineNo:3, x:2, oldText: '', newText: '  '},
    {lineNo:3, x:9, oldText: '', newText: ')'},
  ],
}).text);
```

Produces:

```clojure
(let [a 1]
  ()
    (foo))
```

**Comment by shaunlebron** [comment]
fixed by #181
