### ISSUE TITLE
cold formatting problem

### ISSUE THREAD

**Issue by timothyarmes** [parinfer/parinfer.js#178]
Hi,

I love parinfer, but I've just found an interesting case where I need to force it to misbehave:

This is what I would like:

````
    (cond
      (and (sequential? t1) (sequential? t2))
        (and (= (first t1) (first t2))
             (is-sym (second t1) (last t2))
             (is-sym (last t1) (second t2)))
      :else false)))
````

Note that I wish to indent the condition's `then`  clause  so that it doesn't look like a condition. I can't.

I have to do this instead:

````
(cond
      (and (nil? t1) (nil? t2))
      true
      (and (sequential? t1) (sequential? t2)) (and (= (first t1) (first t2))
                                               (is-sym (second t1) (last t2))
                                               (is-sym (last t1) (second t2)))
     :else false)))
````

Which is much wider.

I doubt there's might that can be done given how parinfer works though...

**Comment by shaunlebron** [comment]
thanks for reporting. a common problem resulting from indentation
communicating _dominant_ siblings rather than formal parents. same problem
happened when trying to indent multi-arity function bodies past the
parameter vectors.

it doesnt seem feasible to allow both. open to ideas though

**Comment by shaunlebron** [comment]
I personally use an empty line to separate cond pairs:

```
(cond
  (and (nil? t1) (nil? t2))
  true
  
  (and (sequential? t1) (sequential? t2))
  (and (= (first t1) (first t2))
    (is-sym (second t1) (last t2))
    (is-sym (last t1) (second t2)))
    
 :else false)))
```

**Comment by shaunlebron** [comment]
Closing.  I think we cannot allow forms to be indented into their siblings.
