### ISSUE TITLE
Parinfer Parens Mode bug

### ISSUE THREAD

**Issue by NightMachinery** [parinfer/parinfer.js#187]
```
-               ("map" . 8614           ; ↦
-                (push pretty-symbol prettify-symbols-alist))))))
+               ("map" . 8614)           ; ↦
+               )) (push pretty-symbol prettify-symbols-alist)))
```
The `-` parts are parinfer's doing. You can take a look at the complete diff log I posted at https://github.com/syl20bnr/spacemacs/issues/10648 . Another prominent example is that parinfer moves comments out of sexps:
```
   (lispyville-set-key-theme
    '(operators
      c-w
-     (escape insert)))
-  ;; (additional-movement normal visual motion)
-  
+     (escape insert)
+     ;; (additional-movement normal visual motion)
+     ))
```

**Comment by shaunlebron** [comment]
thanks!  Can you paste your file into this page below to see if it's really a problem with core, or just the spacemacs plugin?

https://beta.observablehq.com/@shaunlebron/parinfer-test

**Comment by colonelrascals** [comment]
@shaunlebron @NightMachinary I've run both examples through the parinfer test, and it does seem that parenMode moves comments out of sexps. 

Screen shot is attached.

<img width="1293" alt="parenmode" src="https://user-images.githubusercontent.com/24301260/44107238-576adad6-9fbc-11e8-84b2-5af00d230bc9.png">

**Comment by colonelrascals** [comment]
Possibly ignore closing the paren until the comment is escaped?

**Comment by shaunlebron** [comment]
Right, this is the major issue tracked in #92, and have been slumbering on implementation in #175 

P.S. Observable ❤️ 💯

**Comment by shaunlebron** [comment]
Closing as a duplicate of #92
