### ISSUE TITLE
how to add indentation rules for custom forms?

### ISSUE THREAD

**Issue by hoebat** [parinfer/parinfer.js#193]
I noticed that parinfer automatically provides the right indentation for forms like `if` and `with-open` but looking through the source code, I'm not sure where that is specified and how new indentation rules can be added.

**Comment by shaunlebron** [comment]
There are no form-specific indentation rules in parinfer.  I think you were seeing the editor’s own indentation rules, which parinfer respects (but clamps to what it considers valid thresholds).
