### ISSUE TITLE
evil-commentary don't work

### ISSUE THREAD

**Issue by WeissP** [parinfer/parinfer.js#194]
First of all I want to say, this Package is very Cool and interesting : )

"Comment a line without rearranging parens" dosen't work wenn I use `evil-commentary` . And I also test `insert ";;"` , parens will also not be auto reranged.

**Comment by shaunlebron** [comment]
can you file a bug with whichever plugin you’re using?  if you can’t reproduce the bug in the [online demo editor](http://shaunlebron.github.io/parinfer/demo), then it’s a problem with the plugin, not core implementation found in this repo.

**Comment by WeissP** [comment]
> can you file a bug with whichever plugin you’re using? if you can’t reproduce the bug in the [online demo editor](http://shaunlebron.github.io/parinfer/demo), then it’s a problem with the plugin, not core implementation found in this repo.

I use the [evil-commentary](https://github.com/linktohack/evil-commentary) Plugin. And I also want to know, how comments you a line or multi lines?

**Comment by shaunlebron** [comment]
so you’re using emacs.  file a bug with whichever parinfer emacs plugin you’re using

**Comment by WeissP** [comment]
okay
