### ISSUE TITLE
support for comment characters other than semicolon

### ISSUE THREAD

**Issue by oakmac** [parinfer/parinfer.js#195]
The [Janet Language](https://janet-lang.org/) uses the `#` character instead of `;` for comment lines.

It would be nice if Parinfer core supported setting the comment character dynamically via a config option.

For reference: [sublime-text-parinfer PR #37](https://github.com/oakmac/sublime-text-parinfer/pull/37).

**Comment by shaunlebron** [comment]
added in 3.13.0
