### ISSUE TITLE
Align map values

### ISSUE THREAD

**Issue by sheluchin** [parinfer/parinfer.js#196]
I was looking at a Fulcro [tutorial](https://youtu.be/KJsFLmkdRig?t=360) and noticed that map values get auto-aligned:

```clojure
{:a 1
 :b    2}
```

becomes:
```clojure
{:a 1
 :b 2}
```

It doesn't look like Parinfer currently supports this behaviour, but it seems like a sensible approach. I can also see cases where it might not be desirable. Is this feature a consideration?

**Comment by shaunlebron** [comment]
Thanks for asking.  I think I’d like to restrict the scope of formatting to the indentation at the _start_ of a line and trailing close-parens.  It would be a nice to have, but I’m not sure how to squeeze it in nicely.
