### ISSUE TITLE
Add closing quote?

### ISSUE THREAD

**Issue by p4ulcristian** [parinfer/parinfer.js#211]
Hello, I want to close quotes too. Is this possible with parinfer.js? Or do you have any idea how to achieve this behaviour?
I just want the same as with parens. So like `[x` -> `[x]`  it should work for `"x` -> `"x"`

https://github.com/parinfer/parinfer.js/assets/15257711/d9caf227-523a-4a73-8b4d-d9d80276a326

**Comment by shaunlebron** [comment]
I don’t see this being possible.  Programmers don’t use “directional” quotes, only "non-directional" ones.  Imagine if instead of (parens) we used |pipes|.  Plus, multi-line strings can’t be re-indented without mutating their contents.
