### ISSUE TITLE
Plugin for Light Table

### ISSUE THREAD

**Issue by kenny-evitt** [parinfer/parinfer.js#35]
This would be fantastic for [Light Table](http://lighttable.com) and all of the Lispy languages our users use.

Light Table uses Code Mirror internally so maybe this isn't too hard.

**Comment by cldwalker** [comment]
+1 I think this would be doable once #24 lands

**Comment by yogthos** [comment]
:+1:

**Comment by jbeja** [comment]
1+ Yasss!

**Comment by ohAitch** [comment]
:+1:, hadn't realized this was codemirror

**Comment by sanrodari** [comment]
+1

**Comment by shaunlebron** [comment]
alright, this should be unblocked now.  we have a proper library that LightTable can pull in. ~~[details](https://github.com/shaunlebron/parinfer#using-as-a-library)~~

**Comment by yogthos** [comment]
that's pretty awesome!

**Comment by shaunlebron** [comment]
I'm going to close this since we'll just track it on https://github.com/LightTable/LightTable/issues/2049
