### ISSUE TITLE
State caching for performance

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#4]
Editor is slow for large enough files.  Need to cache the state at each line to reduce unnecessary work.

**Comment by shaunlebron** [comment]
we can probably just start at the top-level expression of the cursor.  stop at first dedented expression.

**Comment by shaunlebron** [comment]
I think the key is to identify changed lines (just one range, assuming contiguous changes of course).   processing can then start at the first changed line since there is only one line before that can be changed, which will already be handled by `process-indent` on the first changed line.

After processing the last changed line, I'm pretty sure we can stop at the first line where delim-stack matches the one cached for that line.  We still have to run `process-indent` for that line though.

**Comment by shaunlebron** [comment]
possibly only return the diffed lines.

**Comment by shaunlebron** [comment]
from @oakmac

```
a user is only changing one line at a time
(I'm ignoring copy/paste here)
you can just process the whole file on multi-line copy/paste
the real thing you need to be fast is typing
and the majority of keypresses won't change anything, right?
so how do you quickly cache those out?
that's the part that has to be fast
```

i think the current method results in most of these types of changes causing just one line being processed.

**Comment by shaunlebron** [comment]
seems to be working now.  time to process a single line change in a 400 line file went from 500ms to 23ms.

Need to add tests using a diff format to show line changes

```
 (defn foo [a b]
-  (let [sum (+ a b)]
-    sum))
+  (let [prod (* a b)]
+    prod))
```

after parsing these, we need to verify that the result of `process-text-change` matches the result of `process-text`.

**Comment by oakmac** [comment]
Excellent work :)

**Comment by shaunlebron** [comment]
tests are running here: https://github.com/shaunlebron/parinfer/blob/master/doc/infer-change-tests.md

see docstring for [`format-text-change`](https://github.com/shaunlebron/parinfer/blob/39dddf6716f4a9e775bd5eed5d088bf63f3b9cd3/src/parinfer/format/infer.cljc#L448-L481) for usage.
