### ISSUE TITLE
new plugin: neovim

### ISSUE THREAD

**Issue by snoe** [parinfer/parinfer.js#40]
I put together a plugin for neovim, it's super early but I'd love to get feedback or have some people try it out. This is an amazing tool, thank you!

https://github.com/snoe/nvim-parinfer.js

**Comment by shaunlebron** [comment]
Awesome! :tada:

added it to the site, and will try to test it out tonight, thanks!

**Comment by shaunlebron** [comment]
Installed nvim with this plugin without any problems.  seems to work, thanks!  will look at it some more after the conj.

I'll let you know after #24 is solved so we can integrate better without the submodule
