### ISSUE TITLE
Emacs

### ISSUE THREAD

**Issue by yfeng** [parinfer/parinfer.js#41]

**Comment by shaunlebron** [comment]
Many requests for this, but no one has stepped up yet.  I'm not an emacs user, so I haven't figured it out yet

**Comment by shaunlebron** [comment]
If anyone wants to port Parinfer from Clojure to Emacs Lisp, here are steps:
- check out [Make a Plugin](https://github.com/shaunlebron/parinfer/wiki/Make-a-Plugin) wiki entry for some general guidance
- maybe look at [clomacs](https://github.com/clojure-emacs/clomacs) to use existing clojure implementation

**Comment by lgrapenthin** [comment]
I would really like to do this, but have too little experience in ELisp to cover a port on my own. If an experienced ELisper would like to do this, I'd be glad to help out where I can.

**Comment by lgrapenthin** [comment]
We should consider providing RPC to this impl via a local node server instead of porting.

**Comment by shaunlebron** [comment]
I'm going to close this since @randre03 has committed to try this out, see #58.  Feel free to help there.
