### ISSUE TITLE
Support idiomatic Clojure style

### ISSUE THREAD

**Issue by dmohs** [parinfer/parinfer.js#42]
In the first example [1], change the `:div` to a `:span`:

``` clojure
(defn component []
  (html)
  [:span {:style {:background "#FFF"
                   :color "#000"}}]
  [:h1 "title"])
```

It is now difficult to get the keywords to line up in the map literal.

[1] https://shaunlebron.github.io/parinfer/

**Comment by shaunlebron** [comment]
Not sure what you mean by difficult.  Indentation is manual.  Issue #21 might address this
