### ISSUE TITLE
Add a sockets API?

### ISSUE THREAD

**Issue by refi64** [parinfer/parinfer.js#43]
I'd be interested in making a Parinfer bundle for [Howl](http://howl.io), but Howl's written in MoonScript and can't interface easily with Clojure. Would it be possible to have a sockets-based API to allow other editors to access Parinfer?

**Comment by shaunlebron** [comment]
@snoe has neovim using parinfer through a node host, [see here](https://github.com/snoe/nvim-parinfer.js).  and @oakmac will be doing something similar for sublime.  This is not something I'm familiar with, so maybe one of them can offer advice on this

**Comment by refi64** [comment]
I think that'll work. Thanks!
