### ISSUE TITLE
parinfer should be consistent about how it does or doesn't remove whitespace

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#52]
we currently don't remove whitespace here, represented as an underscore:
- input: `(def b_)`
- output: `(def b)_`

but we do remove whitespace between close-parens:
- input: `(def b []_)`
- output: `(def b [])` <-- whitespace removed

Need to be consistent about this

**Comment by oakmac** [comment]
Should Parinfer just trim all trailing whitespace?

**Comment by shaunlebron** [comment]
no, I think this responsibility belongs to editor features like `.editorconfig`.  parinfer should not prevent people from adding trailing whitespace.  It would be confusing to type some spaces at the end of a line only to have them removed once the cursor leaves the line.

**Comment by shaunlebron** [comment]
This can be solved simply by using the insertion point as the start of the paren trail, then whitespace will be removed instead of just moved.  This will also respect trailing whitespace that is created by the user.
