### ISSUE TITLE
new plugin: emacs-parinfer

### ISSUE THREAD

**Issue by randre03** [parinfer/parinfer.js#58]
Hi Shaun, I've decided this will be a great way to work on my elisp chops so I'm working on emacs-parinfer which is planned to be a minor mode for emacs. Depending on how much work I get done over the coming holiday I might be at a point of making code public in a week or so. Thanks for all the work you have done so far!
Roger
<randre03>

**Comment by shaunlebron** [comment]
thanks!  see #41 for some early talks about connecting it to Node if you want to go that route.

If not, I've written more docs about hooking Parinfer up to an editor here:
https://github.com/shaunlebron/parinfer/tree/master/lib

and send me a github repo link so I link it on the website.

**Comment by anthgur** [comment]
Hey @randre03 (or anyone else), have you thought about using the [cider nrepl client](https://github.com/clojure-emacs/cider/blob/master/nrepl-client.el)? Might be an easier install/run experience than rpc to node. Not sure how it would be performance wise but might be worth exploring.

**Comment by shaunlebron** [comment]
@anthgur thanks!  that might be the easiest way forward

**Comment by lgrapenthin** [comment]
But wouldn't that mean we have to run a JVM to parinfer?

**Comment by shaunlebron** [comment]
right, that would be okay for Clojure users, but there are other Lisp dialect users who would find this dependency strange.

**Comment by dongcarl** [comment]
@randre03 I'm really hoping you are making this native instead of rpcing to node. Is there any update on the progress? Anything we can help with?

**Comment by edpaget** [comment]
Hey all, I had a long train ride, so I started working on this using node for RPC (sorry @dongcarl). It's not usable at all yet, but if anyone wants to help out. Let me know and I'll add you to the repo: https://github.com/edpaget/parinfer-mode

**Comment by shaunlebron** [comment]
Thanks @edpaget!  Added it to the website.

Porting parinfer is nontrivial right now, so I think using node for RPC is good since it's relatively simple (Sublime Text and Neovim are doing this too).  And since Parinfer is still experimental, it also allows us to push bug fixes to the main implementation to affect all editors, which is really nice.

Having said that, I'll help anyone as much as possible if they want to start a proper port.

**Comment by dongcarl** [comment]
@shaunlebron I might give it a go. I'm guessing the first step is doing https://github.com/shaunlebron/parinfer/tree/master/lib#porting-parinfer?

**Comment by arronmabrey** [comment]
@shaunlebron you mention sublime but I haven't seen any links to a sublime plugin. Am I missing something?

**Comment by dongcarl** [comment]
@arronmabrey https://github.com/oakmac/sublime-text-parinfer

**Comment by arronmabrey** [comment]
Thanks!

**Comment by shaunlebron** [comment]
@arronmabrey I'm now maintaining a list of the plugins on the main readme, since it's probably the most important thing to a user to know where they can use it :)

https://github.com/shaunlebron/parinfer#how-to-use-it

**Comment by randre03** [comment]
Sorry for the delay, but repo is now live:  https://github.com/randre03/emacs-parinfer

**Comment by dongcarl** [comment]
@randre03 I might be mistaken but it looks like all the files are in Clojure? Are you planning on translating them to emacs-lisp as you go along? I have some files translated already on my repo if you want to be a contributor: https://github.com/dongcarl/parinfer

**Comment by refi64** [comment]
@randre03 I love this part:

> Right now, this minor mode is not functional so **do not install**.

:)

**Comment by shaunlebron** [comment]
Great work @randre03!  @dongcarl actually started to work on this as well [here](https://github.com/dongcarl/parinfer), so you guys should talk.

**Comment by dongcarl** [comment]
@randre03 did you... port most of Clojure syntax into emacs-lisp?!

**Comment by randre03** [comment]
Check out the README. if I had working ELISP implementations of those
clojure functions listed there then this should be entirely ELISP code.
There are (I suspect) some issues with data structures that need to be
worked out, but I don't see that as especially concerning.

On Wed, Dec 16, 2015 at 9:16 PM, Carl Dong notifications@github.com wrote:

> @randre03 https://github.com/randre03 did you... port most of Clojure
> syntax into emacs-lisp?!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shaunlebron/parinfer/issues/58#issuecomment-165325831
> .

## 

-Roger

**Comment by oakmac** [comment]
Hi folks!

I ported parinfer.js to Emacs Lisp: https://github.com/oakmac/parinfer-elisp

Hopefully someone can use this library to make an awesome Emacs extension :)

**Comment by shaunlebron** [comment]
_an update and petition for help..._

![logo](http://i.imgur.com/4cvg6JZ.png)

## Are we there yet?

Emacs is easily the most requested target editor for Parinfer, but the earlier plugin attempts here have stalled!  This is in no small part to me rewriting Parinfer's core, which essentially pulled the rug out from under their feet.  sorry about that...

## The new core (now available on Emacs-Lisp!)

Parinfer's new core has been [documented in detail](https://github.com/shaunlebron/parinfer/blob/master/lib/parinfer.js.md) to force a stable and deliberate design.  @oakmac has in turn ported the new code to Emacs-Lisp at [parinfer-elisp](https://github.com/oakmac/parinfer-elisp), among several other languages.  This was the hard part, and it's done! :tada:

## Integration Help Wanted

We'd like someone who actually uses Emacs to help us with the final plugin part (i.e. figuring out the integration points with Emacs).  I remain focused on issues concerning the core, while Chris maintains several other ports and plugins (nearly all of them).  So if you'd like to be the hero that brings Parinfer to the most requested editor, here are some ways to get started:
- Check out [parinfer-elisp](the library you'll use)
- Read [How to add parinfer to an editor](https://github.com/shaunlebron/parinfer/tree/master/lib#adding-parinfer-to-an-editor)
- Chat with us at [gitter](https://gitter.im/shaunlebron/parinfer) or (#parinfer on [clojurians slack](http://clojurians.net/))

[![Gitter](https://badges.gitter.im/shaunlebron/parinfer.svg)](https://gitter.im/shaunlebron/parinfer?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Thanks!

**Comment by edpaget** [comment]
I've updated https://github.com/edpaget/parinfer-mode to use the emacs lisp library, not sure it's all the way right yet, but seems to work in my limited testing.

**Comment by shaunlebron** [comment]
thanks @edpaget! listing yours as the main emacs port now
