### ISSUE TITLE
return errors for editors to display

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#62]
- malformed quotes in comments `quoteDanger` -> line number of last parsed offending comment
- unbalanced quotes -> line number of last quote (from top of stack)
- unmatched open parens (only in paren mode) -> line number of unclosed open paren (from top of stack)
- unmatched close parens - we delete these currently

**Comment by shaunlebron** [comment]
@oakmac, you've handled error messages in the past with chessboard and autocomplete.  Could you comment on the following proposal for returning errors?

Proposed result containing errors:

``` js
{
  "text": "...",
  "success": false,
  "errors": [
    {
      "lineNo": 56,
      "x": 12,
      "errorId": 2,
      "errorMsg": "Unclosed quote"
    },
    {
      "lineNo": 120,
      "x": 6,
      "errorId": 1,
      "errorMsg": "Unclosed quote in comments"
    },
    {
      "lineNo": 128,
      "x": 4,
      "errorId": 3,
      "errorMsg": "Unclosed quote"
    }
  ]
}
```

**Comment by oakmac** [comment]
The most important thing is that you want good search results when someone
encounters your error and types "parinfer error 1001" into a search engine.

How many possible errors might there be? If not very many, I might use a
string key like "unclosed-quote" instead of numbers.

If using numbers, I would start at 1000.

**Comment by shaunlebron** [comment]
great, thanks!

**Comment by JoakimLofgren** [comment]
It would be nice if you could get it in different formats like eslint.
E.g. checkstyle, junit and such.

https://github.com/eslint/eslint/tree/master/lib/formatters

**Comment by shaunlebron** [comment]
@JoakimLofgren interesting, thanks! I didn't foresee adding parinfer to a build system that would require exposing warnings like this.  I'll think on whether this is useful.
