### ISSUE TITLE
new plugin: vim

### ISSUE THREAD

**Issue by bhurlow** [parinfer/parinfer.js#65]
Hi @shaunlebron!
Parinfer is absolute fire. Such a wonderful idea and execution. 
Not sure if anyone else has tackled the vim plugin yet bet I took a first pass at it today: https://github.com/bhurlow/vim-parinfer

**Comment by shaunlebron** [comment]
thanks @bhurlow!  :+1: added it to the site :)

**Comment by shaunlebron** [comment]
i'm going to close this issue since it can be tracked from your repo.  thanks for your work :+1:
