### ISSUE TITLE
parinfer-metal

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#66]
Speed has become a limiting factor for Parinfer in real-world use (see below).  Paren Mode takes too long to process files before opening.  And it is becoming cumbersome to meticulously track state changes in `process-text-change` as a means to make up for `process-text` being slow.

![screen shot 2015-12-08 at 6 27 00 pm](https://cloud.githubusercontent.com/assets/688326/11652144/5e05822a-9dd9-11e5-868d-419da152b1f5.png)

Thus, we will implement an imperative/mutable (to the metal) implementation to allow us to:
- see how fast Parinfer can really be
- create a more portable implementation (extra benefit)

@oakmac has been thinking about this for some time.

**Comment by oakmac** [comment]
It is true I have been thinking about this for a while; I think it would be beneficial for the reasons you stated.

One comment: we don't know 100% that Paren Mode is the cause of the slowdown in the above screenshot. My gut says it is likely the cause, but you really need hard metrics to be confident of this sort of thing.

**Comment by shaunlebron** [comment]
The JS implementation of indent mode ([in the metal branch here](https://github.com/shaunlebron/parinfer/tree/metal/lib/metal)) is passing all tests.  Current benchmarks on a file with 2,861 lines (in Chrome):
- cljs: 4965 ms
- js: 120 ms

So the JS implementation can process ~23 lines/ms.  Paren mode should have identical performance.

**Comment by shaunlebron** [comment]
https://github.com/shaunlebron/parinfer/commit/67d61144c2c7ed4b1307e4c9cdf8890cfab303d5 improves the js benchmark to 80 ms

**Comment by shaunlebron** [comment]
metal paren mode is passing all tests, and benchmark takes 110ms.  there's some redundant delim reinsertion happening, so I'll look at fixing this next

**Comment by shaunlebron** [comment]
no marked improvement after removing redundant delim reinsertion

**Comment by shaunlebron** [comment]
everything seems good.  going to move forward with #68
