### ISSUE TITLE
make auto-removing unmatched close-parens an option?

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#79]
auto-removing close-parens enables us to perform the paredit `barf` operation without hotkeys, but it prevents users from typing a right-paren before typing the matching left-paren.

if we can make this an option, it might remove some frustration for newcomers.

this could be difficult to reconcile with our current treatment of paren trails. Notice the `}` below.  This will force me to think more implications about paren trail inference if invalid close-parens can be inserted inside or around them.

``` clj
(foo (bar (baz (boo))}))
```

**Comment by oakmac** [comment]
I dislike this idea :-1: 

Keep it simple; the leading paren determines the closing paren in a deterministic way.
