### ISSUE TITLE
replace cljs-devtools with "Dirac DevTools"

### ISSUE THREAD

**Issue by darwin** [parinfer/parinfer.js#85]
Thanks for mentioning cljs-devtools on the main page.

Recently I have released the first public version. The project is called "Dirac":
https://github.com/binaryage/dirac

Thanks

**Comment by darwin** [comment]
:+1:

**Comment by shaunlebron** [comment]
Cool, thanks.  I wasn't sure whether to use "Dirac" or "Dirac DevTools".  Make a PR based on the referenced commit above if you want to change it.
