### ISSUE TITLE
add Indent Mode option for indenting to next/prev critical tabstop

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#89]
from @snoe on clojurians slack:

> I've been thinking about my workflow a bit and I wonder if `indent` and `dedent` functions would be useful in indent-mode because moving things with space is slow and using 2-stop tabs is imprecise.  Basically, ask where are the tab stops that cause structural changes? `|(|let [|attrs {|:style {|:color "green"}])` Is parinfer in a better place to move the line around these stops (or expose the tab stop info) than editors themselves?

We can add a new Indent Mode option `indentCursorLine` with the following possible values:
- `"NEXT_TABSTOP"`
- `"PREV_TABSTOP"`

For example:

``` js
indentMode(text, {cursorLine: 123, indentCursorLine: "NEXT_TABSTOP"})
```

will put together some test cases to verify correct expected behavior with @snoe

**Comment by snoe** [comment]
Typically I find I insert a new line above the form that I want to slurp or am editing a line and then have to correct what's below by moving my cursor down and selecting the form and then moving it to the correct indentation.

So my first thought is to move the next line's form.
`indentMode(text, {cursorLine: 0, indentCursorLine: "NEXT_TABSTOP"})`

Although I can see an argument made for moving the cursor line's form which would mean passing in `cursorLine: 1`

Wrapping in `when`:

``` input
(when test?)|
(let [foo bar]
  foo)
```

``` output
(when test?
  (let [foo bar]
    foo)
```

The example from the comment where I forgot the enclosing `:style` map:

``` input
(let [attrs {:style |{:color :green}
             :background :red}])
```

``` ouput
(let [attrs {:style {:color :green
                     :background :red}}])
```

**Comment by cursive-ghost** [comment]
In general, I think this is a great idea and this is definitely how it should work. But there's lots of trickiness here when multiple lines are selected which all have different indents. Perhaps these markers should only be determined by the indent of the first line in the selection?

**Comment by shaunlebron** [comment]
I agree that the first line should be determinant when multiple are selected

**Comment by snoe** [comment]
If an editor has selected the `let` form in the first example, I think it actually wants to know the tab stops of the first (non-blank) line above the selection. Now it might be the editor or parinfer who determines how to indent the selection, but I imagine it would find the line furthest to the right in the selection and move all selected lines based off that line.

``` clj
(when-let [ok? (test it)]
  (if really?
    (do it)
    (dont it)))

(map {:foo :bar}
     coll)
```

If the `if` is selected indent would move the form inside the `[ok? ..]`
If both the `if` and the `map` were selected I would expect indent to move the `map` into the `when-let` but should the `if` stay still or move into the vector?

**Comment by cursive-ghost** [comment]
Right, those sorts of cases are what I'm thinking of. Or what about if the user has the second half of a line and some following lines selected?

**Comment by cursive-ghost** [comment]
I've implemented this for the next release of Cursive. The indent stops are defined by the line above the first line in the selection. Cursive currently always indents and dedents whole lines, even if the beginning and end of the selection have partial line selections. All open paren types get a tab stop before the paren, to allow aligning with the collection. Vectors, maps and sets get another tab stop right after the opening delimiter, to allow aligning with the contents of the collection. I assume that lists are not used for data, only code, and so they get a tab stop two spaces indented from the start of the open paren (for macros) and if there is a symbol or a keyword followed by another form, they also get a tab stop at the start of that form (for aligning function call parameters). Lines are then indented or dedented such that the first line in the selection is aligned with one of these tab stops. Subsequent selection lines maintain their indentation relative to the first - I don't snap those to tab stops.

I haven't used it much yet, but it seems very nice - I think this is what you want.

**Comment by cursive-ghost** [comment]
After playing with this a bit, I realised that this was not sufficient. You can't just take the last line into account since you may want to align with tab stops from previous lines. However the stops from later lines should shadow previous ones since they're the only ones which matter for indent mode. 

```
(ns test-ns.core
| (:require [some-ns :refer [one two three]]
| | |       [other-ns]))
| | |       ||
```

Notice here how the tab stops from the `:refer` clause are not taken into account. To calculate the stops I'm going back from the line which is to be indented until I find one which starts at column 0, i.e. a top-level form.

**Comment by shaunlebron** [comment]
Thanks for illustrating the tab-stops.  I like the idea that there is a tab-stop at every open-paren and at some amount of spaces ahead of it.  So it's not about finding just the "critical" tab-stops.

Looks like the shadowing is equivalent to only creating tab-stops for open-parens on Indent Mode's paren stack, after parsing the last line before the selection.

**Comment by cursive-ghost** [comment]
I think that's right. Basically, the shadowing removes any which wouldn't create new nestings under indent mode anyway.

I need to look at this again tomorrow, it works well but is quite slow - I'm not sure why that would be.

**Comment by shaunlebron** [comment]
I think I'm going to have indent mode return a `tabstops` attribute if it receives a cursor position.  For example:

``` clj
(def x 1)

(let [{:keys [foo bar]} some-map
       some-vec [1 2 3]]
  (foo bar)
  baz)

(def y 2)
```

It will identify the following open-parens as tabstops if the cursor is on the line with `|` below:

``` clj
(def x 1)

(let [{:keys [foo bar]} some-map
^    ^
       some-vec [1 2 3]]
                ^
  |
  (foo bar)
  baz)

(def y 2)
```

There are some unintuitive corner cases here, but the information is readily available in Parinfer, so I'll return `tabstops` that would look like the following:

``` js
[
  {char: "(", line: 2, x: 0},
  {char: "[", line: 2, x: 5},
  {char: "[", line: 3, x: 16}
]
```

Editors can thus create custom indent/dedent functionality by passing the text and cursor position to Parinfer to get the tabstops described here.  The reason Parinfer may not handle the full indentation operation for you is that we would be crossing into the territory of caring about indentation conventions such as when to use 1-space, 2-space, or indenting to first arg.  An editor can determine these after receiving the positions the relevant open-parens to base them on.

**Comment by cursive-ghost** [comment]
For posterity, here are some additional considerations. Cursive adds the additional tab stops as described above, but they're generally trivial to calculate (one space after `[` and `{`, two after `(`). Parinfer shouldn't return these since they may also be editor config-dependent, for example two cases that I should handle but currently don't is if the user has configured one-space indents for lists, or has configured two-space indents for everything.

The case which is currently problematic is aligning with function call params, e.g.:

```
(println x
         y)
```

Here you really want a tab stop aligning with `x` and `y`, however this is non-trivial to calculate with parinfer as it is currently implemented, and may be difficult for other editors too. It's relatively easy in Cursive because I use a lexer. The logic I currently implement is: if an open paren is followed by a keyword or a symbol, then a space and then something else, all on the same line, then there is an additional tab stop added aligning with the something else (which is probably a parameter to a call).
