### ISSUE TITLE
identify lines to process - for slower ports

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#91]
When ported to languages that cannot meet a 60Hz rate on a ~3000 line file, parinfer must provide some way to just process a subset of the file.  Essentially, the idea is to create a function that takes a line range that was edited, and will return the line range that must be processed.

``` js
parinfer.identifyLinesToProcess(text, {:editLineRange [42, 64]})
;; => [12, 90]
```

We can do this quickly because Parinfer's reader is very fast when no transforms are performed.  

---

This still forces the plugin author to aggregate edits across debounced and invalid calls, described here: https://github.com/shaunlebron/parinfer/issues/75#issuecomment-167716479

**Comment by shaunlebron** [comment]
We can identify top-level expressions through existing bracket navigation functions in some editors as well, assuming they've been optimized:
- [Atom using "scopes"](https://github.com/jasongilman/proto-repl/blob/eafb5df182c48654e8fccf849fe306d2cfd2a174/lib/editor-utils.coffee#L50)
- [Emacs smartparens backward-up-sexp](https://github.com/Fuco1/smartparens/blob/444c89a555b0ca25ff8d06e74665fbbc3a45a8b7/smartparens.el#L5416)
- [Vim-sexp](https://github.com/guns/vim-sexp/blob/b4398689f7483b01684044ab6b55bf369744c9b3/autoload/sexp.vim#L1054-L1080)

**Comment by cursive-ghost** [comment]
Is it the case that edits within a top-level form will always be restricted to the range of that top level form?

In fact, I can think of one counter-example: if you indent an entire top-level form, it will be pulled inside the previous one:

``` clojure
(let [something (expr)])
(when (something)
  (do something))
```

here, if the last two lines are indented in indent mode, the result is:

``` clojure
(let [something (expr)]
  (when (something)
    (do something)))
```

And the first line has been modified. This line is outside the range of the top-level form that was modified.

This is the only special case I can think of right now, at least for indent mode. I don't have a good intuition for how paren mode works in practice.

**Comment by shaunlebron** [comment]
Thanks for the counter-example. This is really tricky and is something that I'll have to think more about.

**Comment by cursive-ghost** [comment]
I'm not sure it's that tricky - I believe this is the only case where a form outside the top level form is modified, at least in indent mode. I'm not sure it's worth trying to detect this case, I'd just always process the range covering the affected top level form and the previous one.

**Comment by shaunlebron** [comment]
I’m going to close this in favor of using parinfer-rust which vim and emacs plugins use for fast whole-file processing.
