### ISSUE TITLE
Cannot insert whitespace in between [] or {}

### ISSUE THREAD

**Issue by Pauan** [parinfer/parinfer.js#93]
I really like the idea of parinfer, but I ran into a bit of an issue when I tried to use it.

---

Input:

```
(defn component []
  (html)
  [ :div { :style { :background "#FFF"
                    :color "#000" } } ]
  [ :h1 "title" ])
```

Output:

```
(defn component []
  (html)
  [ :div { :style { :background "#FFF"
                    :color "#000"}}]
  [ :h1 "title"])
```

This is in Indent Mode.

---

Notice that the closing `}` and `]` have had their whitespace trimmed.

I would prefer if the closing `}` and `]` would keep the same amount of whitespace as the opening `{` and `[` (i.e. the output should be identical to the input)

**Comment by shaunlebron** [comment]
I suppose this is possible, but I'm not sure if anyone else does this: https://github.com/bbatsov/clojure-style-guide

**Comment by Pauan** [comment]
@shaunlebron The example code is Clojure, but I do not actually write Clojure code. The code I write is for a different Lisp dialect, which has different whitespace conventions from Clojure. I apologize for the confusion.

**Comment by shaunlebron** [comment]
@Pauan cool, which Lisp dialect uses this convention?

**Comment by shaunlebron** [comment]
I think in order to support this, there would have to be a configuration flag to trigger different behavior.

**Comment by Pauan** [comment]
@shaunlebron I am designing a language Nulan (which is currently incomplete). It uses whitespace around `[]` and `{}`:

https://github.com/Pauan/nulan/blob/f008287f9ddeeffa0f20aa0d5ec2726303522143/notes/Current%20state.rst

I'm fine with it being configurable.

**Comment by shaunlebron** [comment]
I don’t think I want to maintain this feature as an option.
